kind: pipeline
name: default

steps:
- name: basic drone
  image: python
  commands:
    - pip install flake8
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - true