language: python

python: "3.6"

sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install codecov 
  - pip install pytest 
  - pip install pytest-cov
  - pip install flake8

before_script:
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - pytest --cov=./

after_success:
  - codecov
  
notifications:
  email: false
  slack: minsiansu:$SLACK_TOKEN