language: python

python:
  # - "3.5"
  - "3.6"

sudo: true

addons:
  apt:
    packages:
    - python-pip

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip

install:
  - pip install codecov 
  - pip install pytest 
  - pip install pytest-cov

script:
  - pytest --cov=./

after_success:
  - codecov
  
notifications:
  email: false
  slack: minsiansu:$SLACK_TOKEN