language: python

python: "3.6"

sudo: false

env:
  - TOXENV=py27
  - TOXENV=py36
  - TOXENV=py37

install:
  - pip install tox-travis

script: tox

after_success:
  - codecov
  
notifications:
  email: false
  slack: minsiansu:$SLACK_TOKEN