group: travis_latest
language: python
cache: pip
python:
  - 3.6

matrix:
  allow_failures:
    - python: 3.6
    - python: nightly
    - python: pypy
    - python: pypy3
install:
  - pip install flake8
before_script:
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

addons:
  sonarcloud:
    organization: "siansiansu-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN

script:
  - true  --cov=./
  - sonar-scanner

after_success:
  - codecov

notifications:
  email: false
  slack: minsiansu:$SLACK_TOKEN
    on_success: change 
    on_failure: always 
